"""
anchor.py — Anchor card dataclass and FAISS/numpy index for PSA.

An anchor is a named semantic region of the memory space. Each anchor has a
centroid (L2-normalized) and a card describing its meaning. The AnchorIndex
supports fast nearest-neighbor search over anchor centroids.

FAISS is used when available; falls back to numpy dot-product (slower but
works without the faiss-cpu wheel).
"""

import json
import logging
import os
from dataclasses import asdict, dataclass, field
from typing import List, Optional, Tuple

import numpy as np

logger = logging.getLogger("psa.anchor")

# ── AnchorCard ────────────────────────────────────────────────────────────────


@dataclass
class AnchorCard:
    """
    A named, described semantic region of the memory atlas.

    Cards are generated by an offline model (Qwen2.5-7B-Instruct) during
    atlas induction and describe the meaning, boundaries, and membership
    criteria for their region.
    """

    anchor_id: int
    name: str  # short human-readable label
    meaning: str  # 1-3 sentence description of what belongs here
    memory_types: List[str]  # dominant memory types in this region
    include_terms: List[str]  # terms that signal membership
    exclude_terms: List[str]  # terms that signal non-membership
    prototype_examples: List[str]  # representative memory titles/summaries
    near_but_different: List[str]  # titles that are close but belong elsewhere
    centroid: List[float]  # L2-normalized centroid vector (dim=768)
    memory_count: int = 0  # number of memories assigned to this anchor
    is_novelty: bool = False  # True → novelty/overflow anchor
    status: str = "active"  # "active" | "retired"
    metadata: dict = field(default_factory=dict)

    def to_stable_card_text(self) -> str:
        """
        Stable text used by selector (training + inference).

        Does not include volatile prototype examples, so the selector
        remains valid across atlas rebuilds that refresh examples.
        """
        parts = [f"Anchor: {self.name}", f"Meaning: {self.meaning}"]
        if self.include_terms:
            parts.append(f"Includes: {', '.join(self.include_terms[:8])}")
        if self.exclude_terms:
            parts.append(f"Excludes: {', '.join(self.exclude_terms[:4])}")
        return "\n".join(parts)

    def to_card_text(self) -> str:
        """
        Full card with volatile examples. Used for display and BM25 retrieval.
        """
        text = self.to_stable_card_text()
        if self.prototype_examples:
            text += f"\nExamples: {'; '.join(self.prototype_examples[:3])}"
        return text

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "AnchorCard":
        return cls(**d)


# ── AnchorIndex ───────────────────────────────────────────────────────────────


class AnchorIndex:
    """
    Fast nearest-neighbor search over anchor centroids.

    Uses FAISS IndexFlatIP (inner product == cosine for L2-normalized vectors)
    when faiss-cpu is installed. Falls back to numpy dot-product otherwise.

    All centroids must be L2-normalized before insertion.
    """

    def __init__(self, dim: int = 768):
        self.dim = dim
        self._cards: List[AnchorCard] = []
        self._centroids: Optional[np.ndarray] = None  # shape (n_anchors, dim)
        self._faiss_index = None
        self._use_faiss = self._try_init_faiss()

    def _try_init_faiss(self) -> bool:
        try:
            import faiss  # noqa: F401

            return True
        except ImportError:
            logger.debug("faiss-cpu not installed; using numpy dot-product for anchor search")
            return False

    def build(self, cards: List[AnchorCard]):
        """Build the index from a list of AnchorCards. Replaces existing index."""
        if not cards:
            raise ValueError("Cannot build an empty anchor index.")

        self._cards = list(cards)
        centroids = np.array([c.centroid for c in cards], dtype=np.float32)

        # L2-normalize (guard against already-normalized centroids)
        norms = np.linalg.norm(centroids, axis=1, keepdims=True)
        norms = np.where(norms == 0, 1.0, norms)
        self._centroids = centroids / norms

        # Infer actual dim from data (may differ from __init__ default)
        self.dim = self._centroids.shape[1]

        if self._use_faiss:
            self._build_faiss()
        # numpy path just uses self._centroids directly

    def _build_faiss(self):
        import faiss

        idx = faiss.IndexFlatIP(self.dim)
        idx.add(self._centroids)
        self._faiss_index = idx

    def search(self, query_vec: List[float], top_k: int = 32) -> List[Tuple[int, float]]:
        """
        Find the top-k nearest anchors to a query vector.

        Parameters
        ----------
        query_vec:
            L2-normalized query embedding (length == self.dim).
        top_k:
            Number of anchors to return.

        Returns
        -------
        List of (anchor_id, score) tuples sorted by score descending.
        Score is cosine similarity (inner product of L2-normalized vectors).
        """
        if self._centroids is None:
            raise RuntimeError("Index is not built. Call build() first.")

        k = min(top_k, len(self._cards))
        qvec = np.array(query_vec, dtype=np.float32).reshape(1, -1)
        if qvec.shape[1] != self._centroids.shape[1]:
            raise ValueError(
                f"Query vector dim {qvec.shape[1]} != index dim {self._centroids.shape[1]}"
            )
        norm = np.linalg.norm(qvec)
        if norm > 0:
            qvec = qvec / norm

        if self._use_faiss and self._faiss_index is not None:
            scores, indices = self._faiss_index.search(qvec, k)
            return [
                (self._cards[i].anchor_id, float(scores[0][j]))
                for j, i in enumerate(indices[0])
                if i >= 0
            ]
        else:
            # numpy fallback
            sims = (self._centroids @ qvec.T).flatten()
            top_idx = np.argsort(sims)[::-1][:k]
            return [(self._cards[i].anchor_id, float(sims[i])) for i in top_idx]

    def get_card(self, anchor_id: int) -> Optional[AnchorCard]:
        """Look up an AnchorCard by anchor_id."""
        for card in self._cards:
            if card.anchor_id == anchor_id:
                return card
        return None

    @property
    def size(self) -> int:
        return len(self._cards)

    def save(self, path: str):
        """Persist the index to a directory."""
        os.makedirs(path, exist_ok=True)
        cards_data = [c.to_dict() for c in self._cards]
        with open(os.path.join(path, "anchor_cards.json"), "w") as f:
            json.dump(cards_data, f, indent=2)
        if self._centroids is not None:
            np.save(os.path.join(path, "centroids.npy"), self._centroids)
        logger.debug("AnchorIndex saved to %s (%d anchors)", path, len(self._cards))

    @classmethod
    def load(cls, path: str, dim: int = 768) -> "AnchorIndex":
        """Load a previously saved AnchorIndex from a directory."""
        cards_path = os.path.join(path, "anchor_cards.json")
        centroids_path = os.path.join(path, "centroids.npy")

        if not os.path.exists(cards_path):
            raise FileNotFoundError(f"No anchor_cards.json at {path}")

        with open(cards_path) as f:
            cards_data = json.load(f)
        cards = [AnchorCard.from_dict(d) for d in cards_data]

        idx = cls(dim=dim)
        idx._cards = cards

        if os.path.exists(centroids_path):
            idx._centroids = np.load(centroids_path)
            # Update dim to match actual saved data
            if idx._centroids.ndim == 2:
                idx.dim = idx._centroids.shape[1]
            if idx._use_faiss:
                idx._build_faiss()

        logger.debug("AnchorIndex loaded from %s (%d anchors)", path, len(cards))
        return idx
